name: Pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Instalar o python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.1'

      - name: Instalar dependências
        run: pip install --quiet -r requirements.txt

      - name: Executar testes
        run: pytest -s -x --cov=fast_zero -vv
